name: Static analysis
on: 
  pull_request:
    paths: ['.github/workflows/*.yml', 'github/workflows/*.yaml']
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - run: sleep 120