name: Test
on: 
  pull_request:
    paths: ['go/**/*.go']
jobs:
  run:
    name: Comment JOB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test go/excellent/*.go